<?php
include('logicPHP/Captcha.php');
include('logicPHP/checkConfig.php');
include('logicPHP/checkBan.php');
include('logicPHP/AdminBtn.php');
include('logicPHP/Log.php');
include('logicPHP/badWords.php');
include('logicPHP/Register.php');
include('logicPHP/Login.php');
include('logicPHP/Post.php');
include('logicPHP/deletePost.php');
include('logicPHP/Pagination.php');
include('logicPHP/PaginationBtn.php');
include('logicPHP/Logout.php');
include('logicPHP/TitleName.php');
include('LogicPHP/Notify.php');
include('LogicPHP/GmailAuth.php');
include($_SERVER['DOCUMENT_ROOT'] . '/app/_ADMIN_TOOLS/admin/logicPHP/Check2FA.php');
?>