<?php
include('logicPHP/Captcha.php');
include('logicPHP/checkConfig.php');
include('logicPHP/checkBan.php');
include('logicPHP/CookieandAdmin.php');
include('logicPHP/Log.php');
include('logicPHP/Format.php');
include('logicPHP/badWords.php');
include('logicPHP/Register.php');
include('logicPHP/Login.php');
include('logicPHP/Post.php');
include('logicPHP/deletePost.php');
include('logicPHP/Comment.php');
include('logicPHP/Pagination.php');
include('logicPHP/PaginationBtn.php');
include('logicPHP/Logout.php');
include('logicPHP/TitleName.php');
include('LogicPHP/Notify.php');
?>