<?php
include('logicPHP/Auth.php');
include('logicPHP/Logout.php');
include('logicPHP/Log.php');
include('logicPHP/Users.php');
include('logicPHP/Comment.php');
include('logicPHP/Post.php');
include('logicPHP/List.php');
include('logicPHP/Search.php');
include('logicPHP/Info.php');
include('logicPHP/Api.php');
include('logicPHP/Pagination/Users.php');
include('logicPHP/Pagination/Post.php');
include('logicPHP/SearchUser.php');
?>
