<?php
include('logicPHP/Auth.php');
include('logicPHP/Logout.php');
include('logicPHP/Log.php');
include('logicPHP/Users.php');
include('logicPHP/Comment.php');
include('logicPHP/Post.php');
include('logicPHP/List.php');
include('logicPHP/Search.php');
include('logicPHP/Info.php');
?>
